config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#new"
  post "/text_extract", to: "dishes#text_extract"
  get '/search' => 'search#index'
  get "/image_search", to: "dishes#image_search"
  # hello
  # get "show", to: "dishes#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :menus, only: [:create] do
    resources :dishes, only: [:index , :create]
  end
  resources :dishes, only: [:index, :show] do
    resources :ingredients, only: [ :index, :create]
  end
  resources :feedbacks
end

app/views/pages/new.html.erb
<div class='general-home container' data-controller="notification-subscription" data-notification-subscription-user-id-value="<%= User.first.id %>">
  <div class="logo d-flex justify-content-center flex-column align-items-center">
    <%= image_tag 'logo-foodme.png', class: 'logo-pic' %>
    <div class="title">
      <h1>Food me</h1>
      <p>Take a pic and see the dish</p>
    </div>
  </div>
  <div data-controller="upload">
      <div class="message-card"  data-upload-target="message">
        <p class="message-style" data-notification-subscription-target="message"></p>
      </div>
    <div class='d-flex flex-column align-items-center justify-content-center flex-grow-1' style="margin-top: 40px">
      <div class="burger d-none" data-controller="burger" data-notification-subscription-target='burger'>
        <svg id="burger" width="200" height="200"></svg>
      </div>
      <%= simple_form_for(@menu, url: text_extract_path) do |f| %>
        <label id="upload" class="" data-notification-subscription-target='form'>
          <%= image_tag src="upload.svg"%>
          <span style="display:none;">
            <%=f.input :photo, as: :file, label_html: {class: 'test'}, input_html: { class: "test2", data: {action: "change->upload#changed"} } %>
          </span>
        </label>
        <button class="btn btn-home d-none mt-5" id="upload-submit" data-action="click->upload#clicked" data-upload-target="button" style="animation: fa-beat 1.5s infinite linear;">Food me!</button>
        <span style="display:none;">
          <%= f.button :submit, class:'create-menu' %>
        </span>
      <% end %>
      <label>
        <span data-upload-target="loader" data-notification-subscription-target='spinner' class="spinner d-none text-white fas fa-spinner fa-spin"></span>
      </label>
      <div class="feedback-line">
    <button type="button" class="feedback btn btn-light"><%= link_to "Feedback", new_feedback_path(@feedback)%></button>
  </div>
</div>